// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFCLrplUAimK0IUmtAxXZtf4fBKhIJto',
    appId: '1:286654038416:web:dc4453645751e97408f315',
    messagingSenderId: '286654038416',
    projectId: 'flutter-odc-pro-421613',
    authDomain: 'flutter-odc-pro-421613.firebaseapp.com',
    storageBucket: 'flutter-odc-pro-421613.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoTEmp9d_FqSnEWlY99KxOqmBp8SP9IRM',
    appId: '1:286654038416:android:6416f2ac6b1ffeeb08f315',
    messagingSenderId: '286654038416',
    projectId: 'flutter-odc-pro-421613',
    storageBucket: 'flutter-odc-pro-421613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB42kR867VvsbpWHB4KYbScxUg1McH-PU0',
    appId: '1:286654038416:ios:d75a600e65cd0ef108f315',
    messagingSenderId: '286654038416',
    projectId: 'flutter-odc-pro-421613',
    storageBucket: 'flutter-odc-pro-421613.appspot.com',
    iosBundleId: 'com.example.odcPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB42kR867VvsbpWHB4KYbScxUg1McH-PU0',
    appId: '1:286654038416:ios:d75a600e65cd0ef108f315',
    messagingSenderId: '286654038416',
    projectId: 'flutter-odc-pro-421613',
    storageBucket: 'flutter-odc-pro-421613.appspot.com',
    iosBundleId: 'com.example.odcPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLFCLrplUAimK0IUmtAxXZtf4fBKhIJto',
    appId: '1:286654038416:web:6df79f53f24ea8cb08f315',
    messagingSenderId: '286654038416',
    projectId: 'flutter-odc-pro-421613',
    authDomain: 'flutter-odc-pro-421613.firebaseapp.com',
    storageBucket: 'flutter-odc-pro-421613.appspot.com',
  );
}
